export const ERROR_CODES = {
  // 400
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_FILE_SIZE: 'INVALID_FILE_SIZE',

  // 401
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // 403
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMPLOYER_NOT_APPROVED: 'EMPLOYER_NOT_APPROVED',

  // 404
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',

  // 409
  CONFLICT: 'CONFLICT',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',
  ALREADY_APPLIED: 'ALREADY_APPLIED',

  // 422
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  JOB_DEADLINE_PASSED: 'JOB_DEADLINE_PASSED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // 429
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // 500
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  S3_ERROR: 'S3_ERROR',
} as const;
